shinyUI(pageWithSidebar(
  headerPanel("Project Gutenberg Distributed Proofreading ocrdiff2 small dataset"),
  sidebarPanel(
    h2("Changes"),
    checkboxInput("all", "Select All", value = TRUE),
    uiOutput("changeSelector")
  ),
  mainPanel(
    h2("Getting Started"),
    p("Select change types from the sidebar. Selected change types will be added to create a metric to compare one round of proofreading with the next."),
    p("Try removing ", tags$b("NEWLINE_SPLIT"), ", ", tags$b("TOTAL_MISMATCH"), " and ", tags$b("XXLARGE_DIFF"), " which all have pathological cases."),
    p("In the PGDP community there is much discussion of \"unimportant\" change types. This tool is an effort to let people experiment with the removal of certain change types in a effort to produce a metric with better predictive power. E.g. most people aggree that ", tags$b("ADD_COMMENT"), " should not be counted as a change to the text."),
    h2("Interesting Change Types"),
    p(tags$b("EQUAL"), " is the change type for no change."),
    p(tags$b("TOTAL_MISMATCH"), " is for cases where the whole page differs. You are most likely to see this on type-in projects."),
    p(tags$b("LARGE_DIFF"), ", ", tags$b("XLARGE_DIFF"), ", ", tags$b("XXLARGE_DIFF"), " and ", tags$b("XXXLARGE_DIFF"), " are those with more than 15 words difference, more than 50 words difference, more than 200 words difference, or more than 500 words difference respectively."),
    p(tags$b("NEWLINE_SPLIT"), " is the addition of line breaks. ", tags$b("NEWLINE_DELETE"), " is the removal of line breaks."),
    p(tags$b("ADD_DISCRETIONARY_HYPHEN"), ", ", tags$b("REMOVE_DISCRETIONARY_HYPHEN"), " and ", tags$b("MARK_DISCERETIONARY_HYPHEN"), " are all about the handling of special proofreading symbols \"-*\" and \"*-\" from the ", a(href="http://www.pgdp.net/c/faq/proofreading_guidelines.php", "PGDP Proofreading Guidelines"), "."),
    p(tags$b("CLOTH_DASH"), " and ", tags$b("UNCLOTH_DASH"), " are about adding or removing spaces near \"-\" characters."),
    p(tags$b("ADD_COMMENT"), " and ", tags$b("REMOVE_COMMENT"), " are about handling of [** comments for the book postprocessor to read.] ", tags$b("REMOVE_COMMENT"), " is always an error on the part of the proofreader."),
    p(tags$b("ADD_FORMATTING"), ", ", tags$b("DELETE_FORMATTING"), " and ", tags$b("CHANGE_FORMATTING"), " are about the handling of special formatting directives only used in F* rounds."),
    h2("Data Description"),
    p("This is data from the ", a(href="http://www.pgdp.net", "PGDP"),
      " ",
      a(href="http://www.pgdp.net/wiki/Confidence_in_Page_analysis",
        "Confidence in Page Project"),
      ". Each point represents a project, a complete book, done by the PGDP team. Checking a change type on the left adds the ratio of that change versus the number of words in the book to an overall metric. The graphs compare this metric between successive rounds of proofreading, three proofreading rounds, P1, P2, P3, and two formatting rounds, F1 and F2."),
    p("This is the ", a(href="http://www.pgdp.net/wiki/Confidence_in_Page_Algorithm#Small_Data_Set", "Small Data Set"), "."),
    p("You can see a discussion of a similar metric for a larger dataset at ", a(href="http://www.pgdp.net/wiki/Confidence_in_Page_Algorithm#Round_to_Round_wa.2Fw", "Round to Round wa/w"), "."),
    p("This page prepared by La Monte Henry Piggy Yarroll for ",
      a(href="https://class.coursera.org/devdataprod-016/", "Developing Data Products"),
      " taught by Brian Caffo, PhD, Jeff Leek, PhD, and Roger D. Peng, PhD, of the Johns Hopkins Bloomberg School of Public Health, on Coursera."),
    h2("P1 vs P2"),
    plotOutput('p1Plot'),
    h2("P2 vs P3"),
    plotOutput('p2Plot'),
    h2("P3 vs F1"),
    plotOutput('p3Plot'),
    h2("F1 vs F2"),
    plotOutput('f1Plot')
  )
))
